version: '3'
services:
  web:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
     ports:
      - "5432:5432"
